#!/bin/sh

if [ $(whoami) != "root" ]; then
        which sudo > /dev/null 2>&1
        if [ $? != 0 ]; then
                echo "Please install sudo or run under root"
                exit 1
        fi
fi

if [ $(whoami) = "root" ]; then
        which sudo > /dev/null 2>&1
        if [ $? != 0 ]; then
                apt-get -y update
                apt-get -y upgrade
		apt-get install -y sudo
        fi
fi

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get install -y curl git make g++ autoconf automake autotools-dev autoconf automake libtool  libboost-all-dev libssl-dev libdb-dev libdb++-dev libdb++-dev libminiupnpc-dev libgmp3-dev

if [ $(free -m | grep "[S]wap:" | awk '/^.*/{print $2}') -lt 1998 ]; then

sudo swapoff -a
sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=2000
sudo mkswap /var/swap.img
sudo swapon /var/swap.img
sudo chmod 0600 /var/swap.img
sudo chown root:root /var/swap.img

fi

sudo cp -r src/boost/boost/* /usr/include/boost/

MAX_PARALLEL=`cat /proc/cpuinfo | awk '/^processor/{print $3}' | wc -l`

cd src
curl -L http://www.openssl.org/source/openssl-1.0.1b.tar.gz -o ./openssl.tgz
tar zxvf openssl.tgz
cd openssl-1.0.1b/
./config
make -j${MAX_PARALLEL}
cd ../..

chmod 755 src/leveldb/build_detect_platform && chmod 755 src/secp256k1/autogen.sh   &&  cd src/leveldb &&     make -j${MAX_PARALLEL} libleveldb.a libmemenv.a &&  cd ../.. && cd src &&  make -j${MAX_PARALLEL} -f makefile.unix OPENSSL_INCLUDE_PATH=openssl-1.0.1b/include OPENSSL_LIB_PATH=openssl-1.0.1b USE_UPNP=

strip PayDayd
cd ..
sudo mkdir -p /usr/bin
sudo mkdir -p /usr/local/bin
sudo rm -f /usr/bin/pdd
sudo rm -f /usr/local/bin/pdd
sudo rm -f /usr/local/bin/pdd_sure_run
sudo cp src/PayDayd /usr/local/bin/pdd
sudo ln -s /usr/local/bin/pdd /usr/bin/pdd
sudo chmod +x config_basic config_masternode utils pdd_sure_run
sudo cp pdd_sure_run /usr/local/bin/
sudo mkdir -p /usr/local/lib/pdd/
sudo cp utils /usr/local/lib/pdd/
