#!/bin/bash
. ./utils
echo "Initial PayDay daemon config"

killall -9 pdd
wait_pdd_stops
mkdir -p ~/.PayDay/
echo -en "rpcuser=PayDayrpc\nrpcpassword=" > ~/.PayDay/PayDay.conf && echo microtime | md5sum | base64 >> ~/.PayDay/PayDay.conf
echo "server=1" >> ~/.PayDay/PayDay.conf
pdd -daemon
sleep 1
wait_pdd_starts

crontab -l  | grep -v pdd > /tmp/pdd.cron
echo "@reboot pdd -daemon ">> /tmp/pdd.cron
echo "*/2 * * * *  pdd -daemon ">> /tmp/pdd.cron
crontab /tmp/pdd.cron
rm -f /tmp/pdd.cron
