#!/bin/bash
. ./utils

pdd ping > /dev/null 2>&1

if [ $? -ne 0 ]; then
   pdd -daemon > /dev/null 2>&1
   sleep 1
   wait_pdd_starts
fi

echo
node=`pdd getaddressesbyaccount "" |  grep -oe "[0-9a-zA-Z]*"`
echo Masternode address $node > ~/masternode_info.txt
key=`pdd masternode genkey`
pk=`pdd dumpprivkey $node`

echo "Stopping daemon"
pdd stop

wait_pdd_stops

echo "Configuring masternode"

echo Masternode key $key >> ~/masternode_info.txt
echo masternodeprivkey=$key >> ~/.PayDay/PayDay.conf
echo masternode=1 >> ~/.PayDay/PayDay.conf
echo masternodesoftlock=1 >> ~/.PayDay/PayDay.conf

echo "Starting daemon"
pdd -daemon
sleep 1
wait_pdd_starts

echo Masternode wallet private key $pk >> ~/masternode_info.txt
echo Your masternode data stored in ~/masternode.info.txt
cat ~/masternode_info.txt
